const SUCCESS = "00";
const SUCCESS_MSG = "Success";
const INVALID_DETAILS = "01";
const INVALID_DETAILS_MSG = "Invalid Details";
const DB_ERROR = "02";
const DB_ERROR_MSG = "DB Connection Issue";


module.exports = {
    DB_ERROR: DB_ERROR,
    DB_ERROR_MSG: DB_ERROR_MSG,
    INVALID_DETAILS: INVALID_DETAILS,
    INVALID_DETAILS_MSG: INVALID_DETAILS_MSG,
    SUCCESS: SUCCESS,
    SUCCESS_MSG: SUCCESS_MSG
};